import numpy as np

# Path to your SMPLH model npz file (contains faces array)
npz_path = "third_party/amass/body_models/smplh/neutral/model.npz"

# Load the npz file
model_data = np.load(npz_path, allow_pickle=True)

# Extract faces (usually under key 'f')
faces = model_data['f']

# Save as smpl_faces.npy in the current directory
np.save('smpl_faces.npy', faces)
print(f"Saved smpl_faces.npy with shape {faces.shape} (generated by get_smpl_faces.py)")
